Import numpy

In [37]:
import numpy as np

In [38]:

a=np.array([[1,2,3],[2,3,4,]])
b=np.zeros((2,3))
c=np.ones((2,3))
d=np.arange(0,10,2)
e=np.linspace(0,10,5)
f=np.eye(3)
e=np.full((2,3),5)
f=np.random.rand(2,3)
g=np.random.randint(0,10,(2,3))


print("------a------\n",a)
print("------b------\n",b)
print("------c------\n",c)
print("------d------\n",d)
print("------e------\n",e)
print("------f------\n",f)
print("------g------\n",g)

------a------
 [[1 2 3]
 [2 3 4]]
------b------
 [[0. 0. 0.]
 [0. 0. 0.]]
------c------
 [[1. 1. 1.]
 [1. 1. 1.]]
------d------
 [0 2 4 6 8]
------e------
 [[5 5 5]
 [5 5 5]]
------f------
 [[0.2383033  0.78308556 0.80226907]
 [0.91666766 0.88690866 0.9512059 ]]
------g------
 [[4 6 3]
 [5 8 9]]


In [39]:
a = np.array([1, 2, 3]) #(1,3)
b = np.array([[1, 2, 3], [4, 5, 6]]) #(2,3)
c = np.zeros((3, 4)) #(3,4)
d = np.arange(0, 10, 2) #(1,5)
e = np.linspace(0, 1, 5) #(1,5)
f = np.eye(3) #(3,3)
g = np.random.randn(4, 3) #(4,3)
h = np.array([[1], [2], [3]]) #(3,1)



#ndim = number of dimensio(for 2*2*2 metrics it will be 3d=3) 
#d's data type = int

In [ ]:
x = np.arange(12)

p = x.reshape(2, 6) #(2,6)
q = x.reshape(6, -1) #(6,2)
r = x.reshape(-1, 1) #(12,1)
s = x.reshape(3, 4).T #(4,3)
t = x.reshape(2, 3, 2) #(2,3,2)   ndim = 3
u = x.reshape(5, 3) #error because 5*3=15 but there is only 12 element

In [ ]:
m = np.arange(12).reshape(3, 4)

a1 = m[0]          #(1,4)    [0,1,2,3]
a2 = m[1, 2]       #(1,)     [6]
a3 = m[:, 0]       #(3,1)    [[0],[4],[8]]
a4 = m[1:, :2]     #(2,2)       [[4,5],[8,9]]
a5 = m[:, -1]      #()
a6 = m[::2]        #
a7 = m[:, 1:3]     #